### ISSUE TITLE
Add blog/announcements type of thing

### ISSUE THREAD

**Issue by zautumnz** [marxism/marxist.space#11]
This should happen _before_ v2, to explain what we're doing and why.

**Comment by aeshthetic** [comment]
Is there a convenient way to integrate this using jekyll's blogging functionality without stepping on what already exists in the repository?

Edit: Seems like there should be, since all we'd really need to do is create a _posts and a layout to render them

**Comment by zautumnz** [comment]
Yeah, but everything else in here will be gone in v2. It might be easier to just implement an announcements thing along with the rest of the new SSR UI.

EDIT: Oh right, I just said it has to happen before v2. Still, I think it'll make sense to move it over after.

**Comment by aeshthetic** [comment]
Will implementing a blog with Jekyll be alright then?

**Comment by zautumnz** [comment]
Yep

**Comment by zautumnz** [comment]
Closed by #15
