### ISSUE TITLE
Deploying locally with jekyll serve does not utilize the default layout or serve the README as the index

### ISSUE THREAD

**Issue by aeshthetic** [marxism/marxist.space#13]
# Is this a feature request or a bug?
Bug
# Expected behavior:
Cloning the repository and running `jekyll serve` should produce a locally hosted site identical to https://marxist.space
# Actual behavior:
Cloning and running `jekyll serve` renders a sitemap at the index, and pages that don't have the default layout (and therefore no CSS) applied to them. Furthermore, jekyll complains about the `{% seo %}` on line 5 of the default layout.

**Comment by aeshthetic** [comment]
I was able to get the expected results by pulling in the `jekyll-readme-index` plugin and adjusting the config to set the default layout as the default

**Comment by aeshthetic** [comment]
Fixed the SEO problem by including the jekyll-seo-tag plugin in the config

**Comment by zautumnz** [comment]
Github Pages includes these plugins by default, so I didn't have them in the config: https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins
