### ISSUE TITLE
Docker + maybe K8s deployment examples

### ISSUE THREAD

**Issue by zautumnz** [marxism/marxist.space#31]
I'm just running this the old-fashioned way, running Node on a VPS behind Nginx, but it might be nice to include a Docker build example and possibly Kubernetes deployments.

Related: #6

**Comment by Nutomic** [comment]
You can probably copy the docker and ansible folders from here, with some adjustments in the Dockerfile.

https://yerbamate.dev/nutomic/joinpeertube
