### ISSUE TITLE
Collection of Articles

### ISSUE THREAD

**Issue by Nutomic** [marxism/marxist.space#4]
I just uploaded a document with a lot of articles and some documentaries that I collected over the years. A lot on the Soviet Union, China and North Korea, but also more general stuff. Not sure which of this would be relevant for you, but feel free to copy anything you want.

https://0xacab.org/snippets/802

**Comment by zautumnz** [comment]
This is awesome, thank you! I'm definitely going to mine it for more resources.

**Comment by dessalines** [comment]
Sweet, I'm gonna add a bunch of these too.

**Comment by Nutomic** [comment]
Maybe I should put my collection into a git repo of my own, but I'm a bit too lazy to maintain yet another project...

**Comment by zautumnz** [comment]
Hey that's why dessaline's essays repo and this repo exist, but it'd always be cool to have more! I'm going to leave this issue open until I have time to actually go through your links and sort them out into marxist.space; that'll probably be sometime this weekend. Thanks again man!
