### ISSUE TITLE
Data storage

### ISSUE THREAD

**Issue by zautumnz** [marxism/marxist.space#7]
We'll need some kind of data storage. It'd be nice to avoid a database and keep flat files (JSON, YAML, or TOML) in the repo so folks can still contribute easily.

**Comment by aeshthetic** [comment]
Do you think keeping flat files would make contribution easier than, say, using a database but providing a convenient and user-friendly frontend on the site for adding things?

**Comment by zautumnz** [comment]
Having UI for contributions would mean also having accounts, roles, etc., which makes it immediately a much bigger task.

**Comment by aeshthetic** [comment]
That's true. However, I think it'd at least be a good idea to provide some sort of front-facing way of making suggestions so that people who know how to use GitHub can review those suggestions and implement them as necessary.

**Comment by zautumnz** [comment]
How about a submission form that opens an issue?

**Comment by aeshthetic** [comment]
Perfect!
